# Generated by Django 2.2.5 on 2019-09-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('url_facebook', models.URLField(blank=True)),
                ('url_Youtube', models.URLField(blank=True)),
                ('url_Instagram', models.URLField(blank=True)),
                ('url_Twitter', models.URLField(blank=True)),
                ('url_web', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('is_bloqueado', models.BooleanField(default=False, verbose_name='Login Bloqueado')),
                ('url_imagen_logo', models.URLField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('url_imagen_cabecera', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
