# Generated by Django 2.2.5 on 2019-09-15 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresas', '0002_empresas_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
