# Generated by Django 2.2.5 on 2019-09-20 18:14

import appEmpresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresas', '0003_auto_20190915_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='url_imagen_cabecera',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='url_imagen_logo',
        ),
        migrations.AddField(
            model_name='empresas',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to=appEmpresas.models.upload_location, verbose_name='Imagen de cabecera'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='imagen_logo',
            field=models.ImageField(blank=True, null=True, upload_to=appEmpresas.models.upload_location, verbose_name='Logo'),
        ),
    ]
