# Generated by Django 2.2.5 on 2019-09-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0003_auto_20190910_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
