# Generated by Django 2.2.5 on 2019-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0005_auto_20190912_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='url_imagen_perfil',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de usuario'),
        ),
    ]
