# Generated by Django 2.2.5 on 2019-09-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0006_auto_20190914_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_bloqueado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_deuda',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_Instagram',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_Pinterest',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_Twitter',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_Youtube',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_imagen_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='url_web',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('latitud', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('url_facebook', models.URLField(blank=True)),
                ('url_Youtube', models.URLField(blank=True)),
                ('url_Instagram', models.URLField(blank=True)),
                ('url_Twitter', models.URLField(blank=True)),
                ('url_Pinterest', models.URLField(blank=True)),
                ('url_web', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('is_bloqueado', models.BooleanField(default=False, verbose_name='Login Bloqueado')),
                ('is_deuda', models.BooleanField(default=False, verbose_name='Posee Deuda')),
                ('url_imagen_perfil', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
