# Generated by Django 2.2.5 on 2019-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0007_auto_20190914_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
