# Generated by Django 2.2.5 on 2019-09-20 17:04

import appUsuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0008_profile_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url_imagen_perfil',
        ),
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=appUsuarios.models.upload_location),
        ),
    ]
